/**
 * Git engine — branches, worktrees, single-commit executions, revert/undo,
 * merge to main, changed files. One managed repo (REPO_PATH), worktrees under
 * VAR_DIR/worktrees/<branch>. All mutating callers must hold the branch
 * mutation lock (bus.withBranchLock).
 */
import fs from 'node:fs';
import path from 'node:path';
import { simpleGit, type SimpleGit } from 'simple-git';
import { env } from '@/lib/env';
import { activeBackend } from '@/lib/site';

const RESERVED_BRANCH_NAMES = new Set(['main', 'master', 'www', 'api', 'cms', 'mail', 'ns1', 'ns2']);
const BRANCH_RE = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;

/** Author/committer identity for any commit-creating git op (see git/identity.ts). */
export interface GitIdentity {
  name: string;
  email: string;
}

/**
 * simple-git bound to an author identity for BOTH author and committer — the
 * container has no git config, so without this any commit fails with "empty
 * ident name". Only what git needs is passed (a full process.env spread leaks
 * EDITOR, which simple-git rejects as unsafe).
 */
function gitAs(dir: string, id: GitIdentity): SimpleGit {
  // allowUnsafeEditor: simple-git blocks GIT_EDITOR by default because an
  // attacker-controlled value executes code — ours is the constant 'true'.
  return simpleGit(dir, { unsafe: { allowUnsafeEditor: true } }).env({
    PATH: process.env.PATH ?? '',
    HOME: process.env.HOME ?? '',
    GIT_AUTHOR_NAME: id.name,
    GIT_AUTHOR_EMAIL: id.email,
    GIT_COMMITTER_NAME: id.name,
    GIT_COMMITTER_EMAIL: id.email,
    // Never open an editor (rebase --continue keeps the original message)
    GIT_EDITOR: 'true',
  });
}

/** DNS-safe label usable as subdomain AND git branch (plan §5). */
export function validateBranchName(name: string): string | null {
  if (!BRANCH_RE.test(name)) {
    return 'Branch names must be DNS-safe labels: lowercase letters, digits, hyphens (1–63 chars, no leading/trailing hyphen).';
  }
  // v- = historical checkouts, c- = per-chat work branches
  if (RESERVED_BRANCH_NAMES.has(name) || name.startsWith('v-') || name.startsWith('c-')) {
    return `"${name}" is reserved.`;
  }
  return null;
}

function repoGit(): SimpleGit {
  const repoPath = path.resolve(env().REPO_PATH);
  // Refuse to operate on a REPO_PATH that isn't its own repository — git
  // would silently walk up to a parent repo (e.g. the CMS checkout when
  // pointing at examples/ in-tree). scripts/setup-dev-site.sh creates a
  // proper copy.
  if (!fs.existsSync(path.join(repoPath, '.git'))) {
    throw new Error(
      `REPO_PATH (${repoPath}) is not a git repository. Use scripts/setup-dev-site.sh to create a git-inited working copy.`,
    );
  }
  ensureRepoExcludes(repoPath);
  return simpleGit(repoPath);
}

/**
 * Build artifacts the preview dev servers generate inside worktrees. The
 * managed repo may lack a .gitignore (it's the user's site), so without these
 * `commitExecution`'s add -A sweeps them into execution commits — and merging
 * such a commit into a branch whose worktree has the same paths untracked
 * fails with "untracked working tree files would be overwritten".
 * .git/info/exclude is repo-local (never committed) and shared by all
 * worktrees.
 */
// package-lock.json: generated by sandbox `npm install` runs; excluding it is
// a no-op when the site repo tracks its lockfile, and stops generated ones
// from being swept into execution commits (and later blocking merges as
// untracked files in the target checkout) when it doesn't.
// Framework artifacts (.astro/, dist/, …) come from the active site backend.
const COMMON_EXCLUDES = ['node_modules/', '.DS_Store', 'package-lock.json'];
const EXCLUDE_MARKER = '# cms-agent managed excludes';
let excludesEnsured = false;

function ensureRepoExcludes(repoPath: string): void {
  if (excludesEnsured) return;
  excludesEnsured = true;
  try {
    const excludeFile = path.join(repoPath, '.git', 'info', 'exclude');
    const current = fs.existsSync(excludeFile) ? fs.readFileSync(excludeFile, 'utf8') : '';
    // Append entries individually — repos written by older versions already
    // carry the marker but may lack newer entries.
    const repoExcludes = [...COMMON_EXCLUDES, ...activeBackend().extraExcludes];
    const lines = new Set(current.split('\n').map((l) => l.trim()));
    const missing = repoExcludes.filter((e) => !lines.has(e));
    if (missing.length === 0 && current.includes(EXCLUDE_MARKER)) return;
    fs.mkdirSync(path.dirname(excludeFile), { recursive: true });
    const head = current.includes(EXCLUDE_MARKER) ? '' : `${EXCLUDE_MARKER}\n`;
    fs.appendFileSync(
      excludeFile,
      `${current.endsWith('\n') || current === '' ? '' : '\n'}${head}${missing.join('\n')}\n`,
    );
  } catch {
    // Best-effort: a failure here only means commits may include artifacts
  }
}

export function worktreeDir(branch: string): string {
  return path.join(path.resolve(env().VAR_DIR), 'worktrees', branch);
}

/** Local git branches eligible as CMS target branches (no work/system refs). */
export async function listRepoBranches(): Promise<string[]> {
  const branches = await repoGit().branchLocal();
  return branches.all.filter(
    (b) => !b.startsWith('c-') && !b.startsWith('v-') && BRANCH_RE.test(b),
  );
}

export async function defaultBranch(): Promise<string> {
  const git = repoGit();
  const branches = await git.branchLocal();
  if (branches.all.includes('main')) return 'main';
  if (branches.all.includes('master')) return 'master';
  return branches.current;
}

/** Create the git branch (from `base`, default main) if missing. */
export async function ensureBranch(branch: string, base?: string): Promise<void> {
  const git = repoGit();
  const branches = await git.branchLocal();
  if (!branches.all.includes(branch)) {
    await git.branch([branch, base ?? (await defaultBranch())]);
  }
}

/** Delete a git branch (worktree must be removed first). No-op if absent. */
export async function deleteBranch(branch: string): Promise<void> {
  if (branch === (await defaultBranch())) {
    throw new Error('refusing to delete the default branch');
  }
  try {
    await repoGit().raw(['branch', '-D', branch]);
  } catch {
    // work branches may not exist in git before their first commit
  }
}

/** Historical read-only checkouts use the reserved v-<sha> label (plan §12). */
export function historicalRef(name: string): string | null {
  const m = /^v-([0-9a-f]{7,40})$/.exec(name);
  return m ? m[1] : null;
}

/**
 * Ensure a worktree exists for the branch and return its absolute path.
 * For the default branch, the repo itself is the worktree. `v-<sha>` names
 * produce detached read-only checkouts of that commit (historical preview).
 */
// In-flight creations: concurrent callers (chat handler, preview manager,
// capabilities probe) would otherwise race the exists-check and the second
// `worktree add` fails with "already exists".
const worktreeCreating = new Map<string, Promise<string>>();

export async function ensureWorktree(branch: string, base?: string): Promise<string> {
  const repoPath = path.resolve(env().REPO_PATH);
  if (branch === (await defaultBranch())) return repoPath;

  const dir = worktreeDir(branch);
  if (fs.existsSync(path.join(dir, '.git'))) return dir;

  const inflight = worktreeCreating.get(branch);
  if (inflight) return inflight;
  const creating = (async () => {
    fs.mkdirSync(path.dirname(dir), { recursive: true });
    // Prune stale registrations (e.g. VAR_DIR wiped) before adding
    await repoGit().raw(['worktree', 'prune']);

    const sha = historicalRef(branch);
    if (sha) {
      await repoGit().raw(['worktree', 'add', '--detach', dir, sha]);
    } else {
      await ensureBranch(branch, base);
      await repoGit().raw(['worktree', 'add', dir, branch]);
    }
    return dir;
  })().finally(() => worktreeCreating.delete(branch));
  worktreeCreating.set(branch, creating);
  return creating;
}

export async function removeWorktree(branch: string): Promise<void> {
  const dir = worktreeDir(branch);
  if (fs.existsSync(dir)) {
    await repoGit().raw(['worktree', 'remove', '--force', dir]);
  }
  await repoGit().raw(['worktree', 'prune']);
}

/** HEAD sha of a branch. */
export async function branchSha(branch: string): Promise<string> {
  return (await repoGit().revparse([branch])).trim();
}

/**
 * Stage and commit ALL worktree changes as one self-contained commit
 * (plan §3: one commit per execution). Returns the sha, or null when the
 * worktree is clean (empty execution).
 */
export async function commitExecution(
  branch: string,
  message: string,
  author: GitIdentity,
): Promise<string | null> {
  const dir = await ensureWorktree(branch);
  const git = gitAs(dir, author);
  const status = await git.status();
  if (status.isClean()) return null;
  await git.add(['-A']);
  await git.commit(message);
  return (await git.revparse(['HEAD'])).trim();
}

/** Dirty-file list of an existing worktree DIRECTORY (no worktree creation). */
export async function dirStatus(dir: string): Promise<string[]> {
  const status = await simpleGit(dir).status();
  return status.files.map((f) => f.path);
}

/** Working-tree status of a branch worktree (dirty file list). */
export async function worktreeStatus(branch: string): Promise<string[]> {
  const dir = await ensureWorktree(branch);
  const status = await simpleGit(dir).status();
  return status.files.map((f) => f.path);
}

/** Revert a commit on the branch (new revert commit; never destructive).
 *  A conflicting revert is aborted so the worktree stays clean. */
export async function revertCommit(branch: string, sha: string, author: GitIdentity): Promise<string> {
  const dir = await ensureWorktree(branch);
  const git = gitAs(dir, author);
  try {
    await git.raw(['revert', '--no-edit', sha]);
  } catch (err) {
    await git.raw(['revert', '--abort']).catch(() => {});
    throw err;
  }
  return (await git.revparse(['HEAD'])).trim();
}

/**
 * Merge `source` into `target` with a merge commit; returns the target's new
 * sha. The merge runs inside the checkout that owns `target` — the repo for
 * the default branch, its worktree otherwise (a branch can only be checked
 * out in one place).
 */
export async function mergeInto(source: string, target: string, author: GitIdentity): Promise<string> {
  const main = await defaultBranch();
  let dir: string;
  if (target === main) {
    dir = path.resolve(env().REPO_PATH);
    const git = repoGit();
    const current = (await git.branchLocal()).current;
    if (current !== main) await git.checkout(main);
  } else {
    dir = await ensureWorktree(target);
  }
  const git = gitAs(dir, author);
  const attempt = async () => {
    try {
      await git.merge(['--no-ff', '-m', `Merge ${source} into ${target}`, source]);
    } catch (err) {
      // Leave no half-applied merge behind (conflicts set MERGE_HEAD)
      try {
        await git.merge(['--abort']);
      } catch {
        /* nothing to abort — the merge never started */
      }
      throw err;
    }
  };
  try {
    await attempt();
  } catch (err) {
    // Untracked files in the target checkout blocking incoming tracked ones
    // are build artifacts (e.g. a package-lock.json generated by a preview
    // npm install) — no one edits the managed checkouts by hand. Remove
    // exactly the files git names and retry once.
    const blocked = untrackedMergeCollisions(err);
    if (blocked.length === 0) throw err;
    for (const f of blocked) fs.rmSync(path.join(dir, f), { force: true });
    await attempt();
  }
  return (await git.revparse(['HEAD'])).trim();
}

/**
 * File list from git's "The following untracked working tree files would be
 * overwritten by merge" error (indented lines after the header), [] for any
 * other error.
 */
export function untrackedMergeCollisions(err: unknown): string[] {
  const msg = err instanceof Error ? err.message : String(err);
  if (!/untracked working tree files would be overwritten/.test(msg)) return [];
  const files: string[] = [];
  let inList = false;
  for (const line of msg.split('\n')) {
    if (/untracked working tree files would be overwritten/.test(line)) {
      inList = true;
      continue;
    }
    if (!inList) continue;
    if (/^\s+\S/.test(line)) files.push(line.trim());
    else break;
  }
  return files.filter((f) => !f.includes('..') && !path.isAbsolute(f));
}

/**
 * Materialize a conflicted merge of `source` INTO `branch`'s worktree and
 * leave it unresolved (MERGE_HEAD set, conflict markers in the files) so an
 * agent can resolve and commit it there. Returns the conflicted paths; []
 * when the merge completed cleanly (races: source moved since the check).
 */
export async function beginConflictMerge(
  branch: string,
  source: string,
  author: GitIdentity,
): Promise<string[]> {
  const dir = await ensureWorktree(branch);
  const git = gitAs(dir, author);
  try {
    await git.merge(['--no-ff', '-m', `Merge ${source} into ${branch}`, source]);
    return [];
  } catch {
    const status = await git.status();
    return status.conflicted;
  }
}

/** Abort an in-progress (conflicted) merge in a branch worktree, if any. */
export async function abortMerge(branch: string): Promise<void> {
  try {
    await simpleGit(await ensureWorktree(branch)).merge(['--abort']);
  } catch {
    // no merge in progress
  }
}

/** Outcome of a rebase step: new head OR the conflicted paths blocking it. */
export interface RebaseResult {
  sha?: string;
  conflicts?: string[];
}

/**
 * Rebase `branch` onto `base` in its worktree. On conflicts the rebase stays
 * IN PROGRESS (markers in the files) so they can be resolved and continued;
 * any other failure aborts cleanly and throws. Rewrites the branch history —
 * previously reviewed shas change.
 */
export async function rebaseOnto(
  branch: string,
  base: string,
  author: GitIdentity,
): Promise<RebaseResult> {
  const dir = await ensureWorktree(branch);
  const git = gitAs(dir, author);
  try {
    await git.rebase([base]);
  } catch (err) {
    const status = await git.status();
    if (status.conflicted.length > 0) return { conflicts: status.conflicted };
    try {
      await git.rebase(['--abort']);
    } catch {
      /* rebase never started */
    }
    throw err;
  }
  return { sha: (await git.revparse(['HEAD'])).trim() };
}

/** Stage everything and continue an in-progress rebase (next conflict or done). */
export async function continueRebase(branch: string, author: GitIdentity): Promise<RebaseResult> {
  const dir = await ensureWorktree(branch);
  const git = gitAs(dir, author);
  await git.add(['-A']);
  try {
    await git.rebase(['--continue']);
  } catch (err) {
    const status = await git.status();
    if (status.conflicted.length > 0) return { conflicts: status.conflicted };
    throw err;
  }
  return { sha: (await git.revparse(['HEAD'])).trim() };
}

/** Abort an in-progress rebase, if any. */
export async function abortRebase(branch: string): Promise<void> {
  try {
    await simpleGit(await ensureWorktree(branch)).rebase(['--abort']);
  } catch {
    // no rebase in progress
  }
}

/** True while `dir` has a rebase in progress (rebase state dir exists —
 *  REBASE_HEAD is unreliable: git may leave it behind after completion). */
export async function rebaseInProgress(dir: string): Promise<boolean> {
  const git = simpleGit(dir);
  for (const state of ['rebase-merge', 'rebase-apply']) {
    const p = (await git.raw(['rev-parse', '--git-path', state])).trim();
    if (fs.existsSync(path.isAbsolute(p) ? p : path.join(dir, p))) return true;
  }
  return false;
}

/** Reset a branch (and its worktree) onto its base after a merge (plan §3). */
export async function resetBranchOnto(branch: string, base: string): Promise<void> {
  const dir = await ensureWorktree(branch);
  const git = simpleGit(dir);
  await git.raw(['reset', '--hard', base]);
}

/** Commits `to` has that `from` lacks (rev-list from..to). 0 = up to date. */
export async function branchAheadCount(from: string, to: string): Promise<number> {
  const out = await repoGit().raw(['rev-list', '--count', `${from}..${to}`]);
  return Number.parseInt(out.trim(), 10) || 0;
}

/** Files changed between `base` (default main) and the branch (three-dot). */
export async function changedFiles(branch: string, base?: string): Promise<string[]> {
  const from = base ?? (await defaultBranch());
  const out = await repoGit().raw(['diff', '--name-only', `${from}...${branch}`]);
  return out.split('\n').map((l) => l.trim()).filter(Boolean);
}

/** Refs accepted from the model: branch names, tags, shas — no flags/ranges. */
const SAFE_REF = /^[0-9A-Za-z][0-9A-Za-z._/-]{0,127}$/;
export function assertSafeRef(ref: string): void {
  if (!SAFE_REF.test(ref) || ref.includes('..')) throw new Error(`Invalid git ref: ${ref}`);
}

/** File content at a ref (`git show ref:path`), read-only. */
export async function showFileAtRef(ref: string, filePath: string): Promise<string> {
  assertSafeRef(ref);
  if (filePath.startsWith('-') || filePath.includes('..') || filePath.includes('\0')) {
    throw new Error(`Invalid path: ${filePath}`);
  }
  return await repoGit().raw(['show', `${ref}:${filePath}`]);
}

/** `git show` of a single commit (message + stat + patch), read-only.
 *  Merge commits diff against their first parent — plain `git show` prints
 *  no patch at all for merges, only a combined --cc diff at best. */
export async function showCommit(ref: string): Promise<string> {
  assertSafeRef(ref);
  return await repoGit().raw([
    'show',
    '--no-color',
    '--stat',
    '--patch',
    '--diff-merges=first-parent',
    ref,
  ]);
}

/** Unified diff of a branch against `base` (default main). */
export async function branchDiff(branch: string, base?: string): Promise<string> {
  const from = base ?? (await defaultBranch());
  return await repoGit().raw(['diff', `${from}...${branch}`]);
}

export interface CommitInfo {
  sha: string;
  message: string;
  authorName: string;
  date: string;
}

export interface BranchCommit extends CommitInfo {
  /** True when the commit is already on the target branch (not exclusive). */
  onTarget: boolean;
}

/**
 * Commit list for the git modal: full history of `branch`, with commits that
 * are already on `target` flagged (the UI greys them out). No target (viewing
 * the target branch itself) → everything is "exclusive".
 */
export async function branchCommits(
  branch: string,
  target: string | null,
  maxCount = 50,
): Promise<BranchCommit[]> {
  const all = await branchLog(branch, maxCount);
  if (!target) return all.map((c) => ({ ...c, onTarget: false }));
  const exclusive = new Set(
    (await repoGit().raw(['rev-list', `--max-count=${maxCount}`, `${target}..${branch}`]))
      .split('\n')
      .filter(Boolean),
  );
  return all.map((c) => ({ ...c, onTarget: !exclusive.has(c.sha) }));
}

export async function branchLog(branch: string, maxCount = 50): Promise<CommitInfo[]> {
  const SEP = '\x1f';
  const out = await repoGit().raw([
    'log',
    branch,
    `--max-count=${maxCount}`,
    `--pretty=format:%H${SEP}%s${SEP}%an${SEP}%aI`,
  ]);
  return out
    .split('\n')
    .filter(Boolean)
    .map((line) => {
      const [sha, message, authorName, date] = line.split(SEP);
      return { sha, message, authorName, date };
    });
}

/**
 * Restore an old version: apply the tree of `sha` (optionally only `paths`)
 * onto the branch head as a NEW commit — history is never rewritten.
 */
export async function restoreVersion(
  branch: string,
  sha: string,
  paths: string[] | undefined,
  author: { name: string; email: string },
): Promise<string | null> {
  const dir = await ensureWorktree(branch);
  const git = simpleGit(dir);
  if (paths && paths.length > 0) {
    await git.raw(['checkout', sha, '--', ...paths]);
  } else {
    // whole tree: read old tree into index + working dir, keep history
    await git.raw(['restore', '--source', sha, '--staged', '--worktree', '--', '.']);
  }
  return commitExecution(branch, `Restore ${sha.slice(0, 8)}`, author);
}
